export const dataUserManual = [
    {
        id: 1,
        title: "E-Grade",
        img: "logo-user-manual-1.png",
        short_desc: "Its right PM just action as.",
        editor: "Iwan Sulistiawan",
        version: "1.10",
        content: "Teacher science should to need themselves decision...",
        category: "internal",
        size: "100 MB",
        updated_at: "2023-02-09 08:59:13",
        created_at: "2022-03-29 10:18:41",
        user_id: 1,
    },
    {
        id: 2,
        title: "Absensi",
        img: "logo-user-manual-1.png",
        short_desc: "Its right PM just action as.",
        editor: "Tammy Walker",
        version: "1.7",
        content: "Close would pressure service management...",
        category: "external",
        size: "71 MB",
        updated_at: "2020-06-17 18:26:28",
        created_at: "2019-11-10 09:51:54",
        user_id: 6,
    },
    {
        id: 3,
        title: "User Management",
        img: "logo-user-manual-1.png",
        short_desc: "Since success record include use rich.",
        editor: "Amanda Anderson",
        version: "2.13",
        content: "Reflect continue should only rate event five...",
        category: "external",
        size: "289 MB",
        updated_at: "2020-05-20 17:14:14",
        created_at: "2022-10-06 20:15:51",
        user_id: 7,
    },
    {
        id: 4,
        title: "System Aplication",
        img: "logo-user-manual-1.png",
        short_desc: "Take away again write difference minute.",
        editor: "Peter Miller",
        version: "2.17",
        content: "Garden mention suggest article...",
        category: "internal",
        size: "329 MB",
        updated_at: "2022-09-05 17:07:06",
        created_at: "2022-01-22 05:34:47",
        user_id: 10,
    },
    {
        id: 5,
        title: "Bantuan Subsidi Upah (SPU)",
        img: "logo-user-manual-1.png",
        short_desc: "Growth ready country cut important leave.",
        editor: "Michael Zhang",
        version: "1.8",
        content: "Off let prepare culture moment...",
        category: "external",
        size: "155 MB",
        updated_at: "2021-08-01 10:46:02",
        created_at: "2020-04-17 17:49:57",
        user_id: 7,
    },
    {
        id: 6,
        title: "Asset Management System (AMS)",
        img: "logo-user-manual-1.png",
        short_desc: "Say beyond can everything staff financial.",
        editor: "Rebecca Dillon",
        version: "2.1",
        content: "Process machine by east care...",
        category: "external",
        size: "70 MB",
        updated_at: "2019-12-21 14:53:19",
        created_at: "2022-07-12 12:37:19",
        user_id: 10,
    },
    {
        id: 7,
        title: "E-Grade",
        img: "logo-user-manual-1.png",
        short_desc: "Its right PM just action as.",
        editor: "Iwan Sulistiawan",
        version: "1.10",
        content: "Teacher science should to need themselves decision...",
        category: "internal",
        size: "100 MB",
        updated_at: "2023-02-09 08:59:13",
        created_at: "2022-03-29 10:18:41",
        user_id: 1,
    },
    {
        id: 8,
        title: "Absensi",
        img: "logo-user-manual-1.png",
        short_desc: "Its right PM just action as.",
        editor: "Tammy Walker",
        version: "1.7",
        content: "Close would pressure service management...",
        category: "external",
        size: "71 MB",
        updated_at: "2020-06-17 18:26:28",
        created_at: "2019-11-10 09:51:54",
        user_id: 6,
    },
    {
        id: 9,
        title: "User Management",
        img: "logo-user-manual-1.png",
        short_desc: "Since success record include use rich.",
        editor: "Amanda Anderson",
        version: "2.13",
        content: "Reflect continue should only rate event five...",
        category: "external",
        size: "289 MB",
        updated_at: "2020-05-20 17:14:14",
        created_at: "2022-10-06 20:15:51",
        user_id: 7,
    },
    {
        id: 10,
        title: "System Aplication",
        img: "logo-user-manual-1.png",
        short_desc: "Take away again write difference minute.",
        editor: "Peter Miller",
        version: "2.17",
        content: "Garden mention suggest article...",
        category: "internal",
        size: "329 MB",
        updated_at: "2022-09-05 17:07:06",
        created_at: "2022-01-22 05:34:47",
        user_id: 10,
    },
    {
        id: 11,
        title: "Bantuan Subsidi Upah (SPU)",
        img: "logo-user-manual-1.png",
        short_desc: "Growth ready country cut important leave.",
        editor: "Michael Zhang",
        version: "1.8",
        content: "Off let prepare culture moment...",
        category: "external",
        size: "155 MB",
        updated_at: "2021-08-01 10:46:02",
        created_at: "2020-04-17 17:49:57",
        user_id: 7,
    },
    {
        id: 12,
        title: "Asset Management System (AMS)",
        img: "logo-user-manual-1.png",
        short_desc: "Say beyond can everything staff financial.",
        editor: "Rebecca Dillon",
        version: "2.1",
        content: "Process machine by east care...",
        category: "external",
        size: "70 MB",
        updated_at: "2019-12-21 14:53:19",
        created_at: "2022-07-12 12:37:19",
        user_id: 10,
    },
];
